require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Api::V1::HoursController, :type => :controller do
  it_behaves_like "api_controller"

  # This should return the minimal set of attributes required to create a valid
  # Hour. As you add validations to Hour, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      hoursheet_id: hoursheet.id,
      item_id: item.id,
      value: 5,
    }
  }

  let(:invalid_attributes) {
    {
      hoursheet_id: nil,
      item_id: nil,
      value: nil,
    }
  }

  let!(:hour) { create(:hour, valid_attributes) }
  let!(:hoursheet) { create(:hoursheet) }
  let!(:item) { create(:item) }

  describe "GET index" do
    it "assigns all hours as @hours" do
      get :index, { format: :json }
      expect(assigns(:hours)).to eq([hour])
    end
  end

  describe "GET show" do
    it "assigns the requested hour as @hour" do
      get :show, { id: hour.id, format: :json }
      expect(assigns(:hour)).to eq(hour)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Hour" do
        expect {
          post :create, { hour: valid_attributes, format: :json }
        }.to change(Hour, :count).by(1)
      end

      it "assigns a newly created hour as @hour" do
        post :create, { hour: valid_attributes, format: :json }
        expect(assigns(:hour)).to be_a(Hour)
        expect(assigns(:hour)).to be_persisted
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hour as @hour" do
        post :create, { hour: invalid_attributes, format: :json }
        expect(assigns(:hour)).to be_a_new(Hour)
      end

      it "re-renders the 'new' template" do
        post :create, { hour: invalid_attributes }
        expect(response.status).to eq(422)
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        {
          hoursheet_id: new_hoursheet.id,
          item_id: new_item.id,
          value: 5,
        }
      }

      let!(:new_hoursheet) { create(:hoursheet) }
      let!(:new_item) { create(:item) }

      it "updates the requested hour" do
        put :update, { id: hour.id, hour: new_attributes }
        hour.reload
        expect(hour.hoursheet_id).to eq(new_hoursheet.id)
        expect(hour.item_id).to eq(new_item.id)
        expect(hour.value).to eq(5)
      end

      it "assigns the requested hour as @hour" do
        put :update, { id: hour.id, hour: valid_attributes }
        expect(assigns(:hour)).to eq(hour)
      end
    end

    describe "with invalid params" do
      it "assigns the hour as @hour" do
        put :update, { id: hour.id, hour: invalid_attributes }
        expect(assigns(:hour)).to eq(hour)
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hour" do
      expect {
        delete :destroy, { id: hour.id, format: :json }
      }.to change(Hour, :count).by(-1)
    end

    it "redirects to the hours list" do
      delete :destroy, { id: hour.id, format: :json }
      expect(response.status).to eq(204)
    end
  end

end
