require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Api::V1::HoursheetsController, :type => :controller do
  it_behaves_like "api_controller"

  # This should return the minimal set of attributes required to create a valid
  # Hoursheet. As you add validations to Hoursheet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      month: 1,
      sheet_id: sheet.id,
      user_id: 1,
      year: 2016,
    }
  }

  let(:invalid_attributes) {
    {
      month: nil,
      sheet_id: nil,
      user_id: nil,
      year: nil,
    }
  }

  let!(:sheet) { create(:sheet) }
  let!(:hoursheet) { create(:hoursheet) }

  describe "GET index" do
    it "assigns all hoursheets as @hoursheets" do
      get :index, { format: :json }
      expect(assigns(:hoursheets)).to eq([hoursheet])
    end
  end

  describe "GET show" do
    it "assigns the requested hoursheet as @hoursheet" do
      get :show, { id: hoursheet.id, format: :json }
      expect(assigns(:hoursheet)).to eq(hoursheet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Hoursheet" do
        expect {
          post :create, { hoursheet: valid_attributes, format: :json }
        }.to change(Hoursheet, :count).by(1)
      end

      it "assigns a newly created hoursheet as @hoursheet" do
        post :create, { hoursheet: valid_attributes, format: :json }
        expect(assigns(:hoursheet)).to be_a(Hoursheet)
        expect(assigns(:hoursheet)).to be_persisted
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hoursheet as @hoursheet" do
        post :create, { hoursheet: invalid_attributes, format: :json }
        expect(assigns(:hoursheet)).to be_a_new(Hoursheet)
      end

      it "re-renders the 'new' template" do
        post :create, { hoursheet: invalid_attributes }
        expect(response.status).to eq(422)
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        {
          user_id: 2,
          month: 2,
          year: 2020,
          sheet_id: new_sheet.id,
        }
      }
      let!(:new_sheet) { create(:sheet) }

      it "updates the requested hoursheet" do
        put :update, { id: hoursheet.id, hoursheet: new_attributes }
        hoursheet.reload
        expect(hoursheet.user_id).to eq(2)
        expect(hoursheet.month).to eq(2)
        expect(hoursheet.year).to eq(2020)
        expect(hoursheet.sheet).to eq(new_sheet)
      end

      it "assigns the requested hoursheet as @hoursheet" do
        put :update, { id: hoursheet.id, hoursheet: valid_attributes }
        expect(assigns(:hoursheet)).to eq(hoursheet)
      end
    end

    describe "with invalid params" do
      it "assigns the hoursheet as @hoursheet" do
        put :update, { id: hoursheet.id, hoursheet: invalid_attributes }
        expect(assigns(:hoursheet)).to eq(hoursheet)
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hoursheet" do
      expect {
        delete :destroy, { id: hoursheet.id, format: :json }
      }.to change(Hoursheet, :count).by(-1)
    end
  end

end
