require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Api::V1::SheetManagersController, :type => :controller do
  it_behaves_like "api_controller"

  # This should return the minimal set of attributes required to create a valid
  # SheetManager. As you add validations to SheetManager, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      year: 2000,
      sheet_id: sheet.id,
    }
  }

  let(:invalid_attributes) {
    { year: nil, sheet_id: nil }
  }

  let!(:sheet) { create(:sheet) }
  let!(:sheet_manager) { create(:sheet_manager) }

  describe "GET index" do
    it "assigns all sheet_managers as @sheet_managers" do
      get :index, { format: :json }
      expect(assigns(:sheet_managers)).to eq([sheet_manager])
    end
  end

  describe "GET show" do
    it "assigns the requested sheet_manager as @sheet_manager" do
      get :show, { id: sheet_manager.id, format: :json }
      expect(assigns(:sheet_manager)).to eq(sheet_manager)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SheetManager" do
        expect {
          post :create, { sheet_manager: valid_attributes, format: :json }
        }.to change(SheetManager, :count).by(1)
      end

      it "assigns a newly created sheet_manager as @sheet_manager" do
        post :create, { sheet_manager: valid_attributes, format: :json }
        expect(assigns(:sheet_manager)).to be_a(SheetManager)
        expect(assigns(:sheet_manager)).to be_persisted
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sheet_manager as @sheet_manager" do
        post :create, { sheet_manager: invalid_attributes, format: :json }
        expect(assigns(:sheet_manager)).to be_a_new(SheetManager)
      end

      it "re-renders the 'new' template" do
        post :create, { sheet_manager: invalid_attributes }
        expect(response.status).to eq(422)
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        {
          year: 3000,
          sheet: build(:sheet),
        }
      }

      it "updates the requested sheet_manager" do
        put :update, { id: sheet_manager.id, sheet_manager: new_attributes }
        sheet_manager.reload
        expect(sheet_manager.year).to eq(3000)
      end

      it "assigns the requested sheet_manager as @sheet_manager" do
        put :update, { id: sheet_manager.id, sheet_manager: valid_attributes }
        expect(assigns(:sheet_manager)).to eq(sheet_manager)
      end
    end

    describe "with invalid params" do
      it "assigns the sheet_manager as @sheet_manager" do
        put :update, { id: sheet_manager.id, sheet_manager: invalid_attributes }
        expect(assigns(:sheet_manager)).to eq(sheet_manager)
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sheet_manager" do
      expect {
        delete :destroy, { id: sheet_manager.id, format: :json }
      }.to change(SheetManager, :count).by(-1)
    end
  end

end
