require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Api::V1::SheetsController, :type => :controller do
  it_behaves_like "api_controller"

  # This should return the minimal set of attributes required to create a valid
  # Sheet. As you add validations to Sheet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: "Example Sheet" }
  }

  let(:invalid_attributes) {
    { name: "" }
  }

  let!(:sheet) { create(:sheet, valid_attributes) }

  describe "GET index" do
    it "assigns all sheets as @sheets" do
      get :index, { format: :json }
      expect(assigns(:sheets)).to eq([sheet])
    end
  end

  describe "GET show" do
    it "assigns the requested sheet as @sheet" do
      get :show, { id: sheet.id, format: :json }
      expect(assigns(:sheet)).to eq(sheet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Sheet" do
        expect {
          post :create, { sheet: valid_attributes, format: :json }
        }.to change(Sheet, :count).by(1)
      end

      it "assigns a newly created sheet as @sheet" do
        post :create, { sheet: valid_attributes, format: :json }
        expect(assigns(:sheet)).to be_a(Sheet)
        expect(assigns(:sheet)).to be_persisted
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sheet as @sheet" do
        post :create, { sheet: invalid_attributes, format: :json }
        expect(assigns(:sheet)).to be_a_new(Sheet)
      end

      it "re-renders the 'new' template" do
        post :create, { sheet: invalid_attributes }
        expect(response.status).to eq(422)
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        { name: "Example Updated Sheet" }
      }

      it "updates the requested sheet" do
        put :update, { id: sheet.id, sheet: new_attributes }
        sheet.reload
        expect(sheet.name).to eq("Example Updated Sheet")
      end

      it "assigns the requested sheet as @sheet" do
        put :update, { id: sheet.id, sheet: valid_attributes }
        expect(assigns(:sheet)).to eq(sheet)
      end
    end

    describe "with invalid params" do
      it "assigns the sheet as @sheet" do
        put :update, { id: sheet.id, sheet: invalid_attributes }
        expect(assigns(:sheet)).to eq(sheet)
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sheet" do
      expect {
        delete :destroy, { id: sheet.id, format: :json }
      }.to change(Sheet, :count).by(-1)
    end

    it "redirects to the sheets list" do
      delete :destroy, { id: sheet.id, format: :json }
      expect(response.status).to eq(204)
    end
  end

end
